/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatasetList: typeof import('./src/components/DatasetList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadPane: typeof import('./src/components/UploadPane.vue')['default']
    WaveformViewer: typeof import('./src/components/WaveformViewer.vue')['default']
  }
}

// For TSX support
declare global {
  const DatasetList: typeof import('./src/components/DatasetList.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UploadPane: typeof import('./src/components/UploadPane.vue')['default']
  const WaveformViewer: typeof import('./src/components/WaveformViewer.vue')['default']
}